name: Validate README markers
on: [pull_request, push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          grep "<!-- AUTO-UPDATE-START -->" README.md
          grep "<!-- AUTO-UPDATE-END -->" README.md
