name: Validate README

on:
  pull_request:
    paths:
      - "README.md"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for required marker
        run: |
          if ! grep -q "<!-- AUTO-UPDATE-MARKER -->" README.md; then
            echo "❌ README.md is missing the AUTO-UPDATE-MARKER"
            exit 1
          fi
          echo "✅ README validation passed"
